<a href="https://colab.research.google.com/github/Batumm/Swansea_BigDataMachineLearning/blob/main/2131029_Notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Nicolas Bataille
26/09/2021\
Student number : 2131029

In [79]:
#Imports of needed packages
import numpy as np
import matplotlib.pyplot as plt

In [78]:
#Code needed in order to be able to import files from the Google Drive
!pip install -U -q PyDrive
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials

In [71]:
#Authentication to my Google Account
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

#Task 1.1

3.

In [ ]:
x = 345
print(2*x+5**3)

815


4.

In [ ]:
print("Hello World")

Hello World


5.

In [ ]:
def f(w,x,b):
  return ((w*x)+b)

In [ ]:
print(f(x=345, w=2, b=(5**3)))

815


#Task 1.2

1,2.

In [ ]:
my_list = ["cat", "dog", "hamster", "fish", "bird"]
for i in range(len(my_list)-1, -1, -1):   #Using the len(my_list) allows to add or remove elements without having to manually change the for loop arguments
  print(my_list[i])

bird
fish
hamster
dog
cat


3.

In [ ]:
def equals_100(x):
  if(x == 100):
    return True
  else:
    return False

print(equals_100(x=99))
print(equals_100(x=100))

False
True


4.

In [ ]:
my_dictionnary = {
    'data_name' : 'Animal counts',
    'label' : ["cat", "dog", "fish"],
    'count' : [2, 5, 10]
}

5.

In [ ]:
for i in my_dictionnary:
  print(i, ":")
  print(my_dictionnary[i])
  print(" ")

data_name :
Animal counts
 
label :
['cat', 'dog', 'fish']
 
count :
[2, 5, 10]
 


6.

In [ ]:
print(f'Animal name: {my_dictionnary["label"][1]}, count: {my_dictionnary["count"][1]}')

Animal name: dog, count: 5


#Task 1.3

2.

In [ ]:
matrix_x = np.random.randint(10, size=(2,3))
matrix_y = np.random.randint(10, size=(3,4))

print(matrix_x)
print(" ")
print(matrix_y)

[[5 8 8]
 [6 4 4]]
 
[[0 9 7 9]
 [7 7 5 7]
 [6 3 9 3]]


3.

In [ ]:
matrix_mult = np.matmul(matrix_x, matrix_y)
print(matrix_mult)

[[104 125 147 125]
 [ 52  94  98  94]]


4.

In [ ]:
for i in range(0,len(matrix_mult)):
  print(matrix_mult[i][0])

104
52


#Task 1.4

1.

In [73]:
#Importing the npy file from the Google Drive
downloaded = drive.CreateFile({'id':'1VJE4kmqaINfilcJBkdg6WvUT2zJRTR5t'}) 
downloaded.GetContentFile('Iris_data.npy')

iris = np.load('Iris_data.npy')

2.


In [76]:
print(iris.shape)

(150, 4)


3.